'use client';

export type GoogleFormsActionKey = 'enable-form-trigger' | 'submission-router';
export type GoogleFormsActionBadge = 'Trigger' | 'Workflow';
export type GoogleFormsFieldType = 'text' | 'textarea' | 'select';

export interface GoogleFormsFieldOption {
  label: string;
  value: string;
}

export interface GoogleFormsFormValues {
  [key: string]: string;
}

export interface GoogleFormsFieldDefinition {
  key: string;
  label: string;
  type: GoogleFormsFieldType;
  required: boolean;
  placeholder: string;
  helperText?: string;
  options?: GoogleFormsFieldOption[];
  spanFull?: boolean;
}

export interface GoogleFormsActionDefinition {
  key: GoogleFormsActionKey;
  badge: GoogleFormsActionBadge;
  title: string;
  description: string;
  frontendRule: string;
  steps: string[];
  fields: GoogleFormsFieldDefinition[];
}

export interface GoogleFormsBrowserItem {
  key: GoogleFormsActionKey;
  section: 'Triggers' | 'Workflow';
  title: string;
  description: string;
  badge: GoogleFormsActionBadge;
}

export const GOOGLE_FORMS_ACCOUNT_OPTIONS: GoogleFormsFieldOption[] = [
  { label: 'Primary connected account', value: 'primary_connected_account' },
  { label: 'Work Google account', value: 'work_google_account' },
  { label: 'Support Google account', value: 'support_google_account' },
];

export const GOOGLE_FORMS_ACTION_DEFINITIONS: GoogleFormsActionDefinition[] = [
  {
    key: 'enable-form-trigger',
    badge: 'Trigger',
    title: 'Enable form submission trigger',
    description:
      'Enable automatic detection of new Google Form submissions using the connected account and a known Form ID.',
    frontendRule:
      'The backend uses Google OAuth plus a form identifier and webhook secret to receive form submission events.',
    steps: [
      'User connects the Google account.',
      'User enters the Google Form ID.',
      'Backend prepares the webhook trigger.',
      'Incoming submissions are passed into the workflow.',
    ],
    fields: [
      {
        key: 'connectedAccount',
        label: 'Connected Google account',
        type: 'select',
        required: true,
        placeholder: 'Select connected account',
        options: GOOGLE_FORMS_ACCOUNT_OPTIONS,
      },
      {
        key: 'formId',
        label: 'Form ID',
        type: 'text',
        required: true,
        placeholder: 'Enter Google Form ID',
      },
      {
        key: 'webhookSecret',
        label: 'Webhook secret',
        type: 'text',
        required: false,
        placeholder: 'Optional webhook secret',
        helperText: 'Usually generated by the backend when the connector is saved.',
      },
      {
        key: 'formTitle',
        label: 'Form title',
        type: 'text',
        required: false,
        placeholder: 'Optional form title',
      },
      {
        key: 'triggerSource',
        label: 'Trigger source',
        type: 'select',
        required: false,
        placeholder: 'Choose trigger source',
        options: [
          { label: 'webhook', value: 'webhook' },
          { label: 'manual', value: 'manual' },
        ],
      },
    ],
  },
  {
    key: 'submission-router',
    badge: 'Workflow',
    title: 'Configure submission router',
    description:
      'Route Google Form submissions into the downstream workflow with optional filtering or handling preferences.',
    frontendRule:
      'Google Forms is webhook-driven, so the UI focuses on connecting the form and shaping the submission routing behavior.',
    steps: [
      'User confirms the connected Google account.',
      'User links the target Google Form.',
      'Optional routing settings are applied.',
      'Backend forwards the submission payload to the workflow.',
    ],
    fields: [
      {
        key: 'connectedAccount',
        label: 'Connected Google account',
        type: 'select',
        required: true,
        placeholder: 'Select connected account',
        options: GOOGLE_FORMS_ACCOUNT_OPTIONS,
      },
      {
        key: 'formId',
        label: 'Form ID',
        type: 'text',
        required: true,
        placeholder: 'Enter Google Form ID',
      },
      {
        key: 'routeMode',
        label: 'Route mode',
        type: 'select',
        required: false,
        placeholder: 'Choose route mode',
        options: [
          { label: 'webhook_only', value: 'webhook_only' },
          { label: 'forward_to_workflow', value: 'forward_to_workflow' },
          { label: 'store_only', value: 'store_only' },
        ],
      },
      {
        key: 'responseKey',
        label: 'Response key',
        type: 'text',
        required: false,
        placeholder: 'Optional response key',
      },
      {
        key: 'notes',
        label: 'Notes',
        type: 'textarea',
        required: false,
        placeholder: 'Optional routing notes',
        spanFull: true,
      },
    ],
  },
];

export const GOOGLE_FORMS_BROWSER_ITEMS: GoogleFormsBrowserItem[] = [
  {
    key: 'enable-form-trigger',
    section: 'Triggers',
    title: 'Enable form submission trigger',
    description: 'Detect new form submissions using the connected Google account and webhook-based trigger flow.',
    badge: 'Trigger',
  },
  {
    key: 'submission-router',
    section: 'Workflow',
    title: 'Configure submission router',
    description: 'Shape how incoming Google Form responses are handled and passed into the workflow.',
    badge: 'Workflow',
  },
];

export const DEFAULT_GOOGLE_FORMS_ACTION_KEY: GoogleFormsActionKey = 'enable-form-trigger';

export function getGoogleFormsActionDefinition(actionKey: GoogleFormsActionKey): GoogleFormsActionDefinition {
  return GOOGLE_FORMS_ACTION_DEFINITIONS.find((definition) => definition.key === actionKey) || GOOGLE_FORMS_ACTION_DEFINITIONS[0];
}

export function buildInitialGoogleFormsFormValues(action: GoogleFormsActionDefinition): GoogleFormsFormValues {
  const values: GoogleFormsFormValues = {};
  action.fields.forEach((field) => {
    if (field.type === 'select' && field.required) {
      values[field.key] = field.options?.[0]?.value || '';
      return;
    }
    values[field.key] = '';
  });
  return values;
}
