export const derivedFieldInfo = {
  'Exit IRR': {
    meaning: 'Annualised return expected from asset exit based on acquisition cost, target exit value and holding period.',
    concept: 'Target exit value is compared with acquisition cost and annualised over the holding period between acquisition date and expected sale date.',
    formula: 'Exit IRR = [(Target Exit Value / Acquisition Cost) ^ (1 / Holding Period in Years)] - 1'
  },

  'Acquisition Cost (₹)': {
    meaning: 'Original purchase/acquisition cost of the asset used in exit analysis.',
    concept: 'It is pulled from the Financial Value section for the same Asset ID.',
    formula: 'Linked from Financial Value → Acquisition Cost (₹)'
  },

  'Total Income (₹/yr)': {
    meaning: 'Total annual income generated by the asset before expenses.',
    concept: 'Rental income and other income are added together.',
    formula: 'Rental Income + Other Income'
  },
  'Total Income': {
    meaning: 'Total income generated by the asset before expenses.',
    concept: 'Rental income and other income are added together.',
    formula: 'Rental Income + Other Income'
  },

  'Gross Rental Income (₹/yr)': {
    meaning: 'Annual rental income used for cash flow analysis.',
    concept: 'It is taken from the Revenue & Income section for the same Asset ID.',
    formula: 'Rental Income (₹/yr)'
  },
  'Total Gross Income (₹/yr)': {
    meaning: 'Total annual income before expenses.',
    concept: 'Rental income and other income are added together.',
    formula: 'Gross Rental Income + Other Income'
  },
  'Operating Expenses (₹/yr)': {
    meaning: 'Annual operating cost used in cash flow analysis.',
    concept: 'It is taken from computed Opex in Expenses section.',
    formula: 'Maintenance Cost + Property Tax + Insurance + Utilities + Repairs'
  },
  'Annual Debt Service (₹/yr)': {
    meaning: 'Total annual loan repayment obligation.',
    concept: 'Monthly EMI is multiplied by 12.',
    formula: 'EMI × 12'
  },
  'Net Cash Flow After Debt (₹/yr)': {
    meaning: 'Cash flow remaining after paying operating expenses and debt service.',
    concept: 'NOI is reduced by annual debt service.',
    formula: 'NOI - Annual Debt Service'
  },
  'Free Cash Flow (₹/yr)': {
    meaning: 'Cash flow available after debt service and capex reserve.',
    concept: 'Net cash flow after debt is reduced by capex reserve.',
    formula: 'Net Cash Flow After Debt - Capex Reserve'
  },
  'Cash Yield (%)': {
    meaning: 'Cash flow return as a percentage of opening value.',
    concept: 'Free cash flow is compared with opening value.',
    formula: 'Free Cash Flow ÷ Opening Value × 100'
  },

  'Market Rate (₹/sq ft on carpet area)': {
    meaning: 'Rate per sq ft on carpet area implied by current market value.',
    concept: 'Current market value is divided by carpet area to derive the asset-level market rate.',
    formula: 'Current Market Value (₹) ÷ Carpet Area'
  },
  'Market Rate': {
    meaning: 'Rate per sq ft implied by current market value.',
    concept: 'Current market value is divided by carpet area to derive the asset-level market rate.',
    formula: 'Current Market Value ÷ Carpet Area'
  },
  "Emissions (tCO2e/yr)": {
    "meaning": "Estimated carbon emissions generated from annual energy consumption.",
    "concept": "Energy use is converted into carbon emissions using an emission factor.",
    "formula": "Energy Consumption (kWh/yr) × 0.0007"
  },
  "Compliance Status": {
    "meaning": "Compliance label indicating whether approvals are acceptable.",
    "concept": "Approval status is checked and converted into compliant/review status.",
    "formula": "If Approvals = Approved or Partly Approved → Compliant; otherwise → Review"
  },
  "ESG Risk Score": {
    "meaning": "Composite ESG risk score for the asset.",
    "concept": "Tenant health/safety, climate risk and green certification are converted into a risk score.",
    "formula": "AVERAGE(100 - Tenant Health/Safety Score, Climate Risk Score, Green Certification Risk Score)"
  },
  "Current Market Value (₹)": {
    "meaning": "Estimated current market value of the asset.",
    "concept": "Market rate is applied to carpet area to estimate value.",
    "formula": "Market Rate (₹/sq ft) × Carpet Area (sq ft)"
  },
  "Appreciation/Depreciation (%)": {
    "meaning": "Percentage increase or decrease in value compared with acquisition cost.",
    "concept": "Current market value is compared against acquisition cost.",
    "formula": "(Current Market Value - Acquisition Cost) ÷ Acquisition Cost"
  },
  "Occupancy Income (₹/yr)": {
    "meaning": "Revenue attributable to occupied space.",
    "concept": "Rental income is adjusted by occupancy percentage.",
    "formula": "Rental Income × Occupancy (%)"
  },
  "Opex (₹/yr)": {
    "meaning": "Total operating expenditure for the asset.",
    "concept": "Recurring expense heads are added together.",
    "formula": "Maintenance Cost + Property Tax + Insurance + Utilities + Repairs"
  },
  "Vacant Area (sq ft)": {
    "meaning": "Unoccupied leasable area.",
    "concept": "Leasable area is adjusted by the vacant percentage.",
    "formula": "Leasable Area × (1 - Occupancy %)"
  },
  "EMI (₹/month)": {
    "meaning": "Estimated monthly loan instalment.",
    "concept": "Loan amount, interest rate and assumed 120-month tenure are used to estimate EMI.",
    "formula": "PMT(Interest Rate ÷ 12, Loan Tenure, Loan Amount)"
  },
  "LTV (%)": {
    "meaning": "Loan-to-value ratio showing debt exposure against asset value.",
    "concept": "Outstanding principal is compared with current market value.",
    "formula": "Outstanding Principal ÷ Current Market Value"
  },
  "DSCR": {
    "meaning": "Debt service coverage ratio showing income coverage of debt service.",
    "concept": "NOI is compared with annual debt repayment.",
    "formula": "NOI ÷ (EMI × 12)"
  },
  "Red Flag Score": {
    "meaning": "Overall risk score across risk categories.",
    "concept": "High/Medium/Low risks are converted to numeric values and averaged.",
    "formula": "Average risk score where High = 90, Medium = 60, Low = 25"
  },
  ["NOI (₹/yr)"]: {
    "meaning": "Net operating income generated by the asset.",
    "concept": "Operating income is reduced by operating expenses.",
    "formula": "Occupancy Income + Other Income - Opex"
  },
  "EBITDA (₹/yr)": {
    "meaning": "Earnings before interest, tax, depreciation and amortisation.",
    "concept": "NOI is reduced by insurance expense as per workbook logic.",
    "formula": "NOI - Insurance"
  },
  "Cap Rate (%)": {
    "meaning": "Income yield on the asset based on current market value.",
    "concept": "NOI is compared with current market value.",
    "formula": "NOI ÷ Current Market Value"
  },
  "ROI (%)": {
    "meaning": "Return on investment based on acquisition cost.",
    "concept": "NOI is compared with acquisition cost.",
    "formula": "NOI ÷ Acquisition Cost"
  },
  "Yield (%)": {
    "meaning": "Rental yield based on rental income and current market value.",
    "concept": "Rental income is compared with current market value.",
    "formula": "Rental Income ÷ Current Market Value"
  },
  "Payback Period (yrs)": {
    "meaning": "Years required to recover acquisition cost through NOI.",
    "concept": "Acquisition cost is divided by NOI.",
    "formula": "Acquisition Cost ÷ NOI"
  },
  "Cash-on-Cash Return (%)": {
    "meaning": "Cash return on equity invested after debt servicing.",
    "concept": "NOI after debt service is compared with equity investment.",
    "formula": "(NOI - EMI × 12) ÷ (Acquisition Cost - Loan Amount)"
  },
  "Alerts": {
    "meaning": "Automated warning messages from risk thresholds.",
    "concept": "System checks red flag score, LTV, DSCR and compliance status.",
    "formula": "TEXTJOIN alerts if Red Flag Score > 70, LTV > 0.75, DSCR < 1.25, or Compliance Status is not Compliant"
  },
  "Target Exit Value (₹)": {
    "meaning": "Target value expected at exit.",
    "concept": "Current market value is uplifted by exit assumption.",
    "formula": "Current Market Value × 1.25"
  },
  "Exit IRR (%)": {
    "meaning": "Indicative annualised return until exit.",
    "concept": "Target exit value is compared with acquisition cost and annualised over the holding period between acquisition date and expected sale date.",
    "formula": "Exit IRR = [(Target Exit Value / Acquisition Cost) ^ (1 / Holding Period in Years)] - 1"
  }
};


export const revenueIncomeFieldInfo = {
  'Rental Income': {
    meaning: 'Rent earned from tenants for the asset',
    computed: 'Monthly Rent × Occupied Units or sum of all active lease rents'
  },
  'Occupancy Income': {
    meaning: 'Income linked to occupied space/units',
    computed: 'Occupied Area × Rent per sq ft or Occupied Units × Rent per unit'
  },
  'Escalation Clause': {
    meaning: 'Rent increase condition in lease agreement',
    computed: 'Usually defined as % increase after a period. Example: 5% annual escalation or 15% every 3 years'
  },
  'Collection Efficiency': {
    meaning: 'How much billed revenue is actually collected',
    computed: 'Amount Collected ÷ Amount Billed × 100'
  }
};



